name: Add new issues to Dev Tracker

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    name: Add issue to Dev Tracker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/users/thingy-01/projects/5
          github-token: ${{ secrets.PROJECTS_PAT }}
